import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# `force_ssl` must be set at compile time (Phoenix marks it as compile-env), so it
# lives here rather than in runtime.exs. Behind Gigalixir's and Cloudflare's TLS
# proxies the request arrives as plain HTTP with `X-Forwarded-Proto: https`, which
# `rewrite_on` trusts, so there's no redirect loop.
config :gymrat, GymratWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto], hsts: true]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
